### ISSUE TITLE
Instructions to Run the module

### ISSUE THREAD

**Issue by saket-maheshwary** [qkaren/Adversarial-Network-for-Implicit-Discourse-Relation-Classification-ACL-2017-#1]
Hi, Could you please update the Readme with the instructions as to how to run this module ? It would be very helpful.

`run_gan.py` requires a sys argument. Could you please mention what that argument is ?  I am not able to execute the script `run_gan.py`.

**Comment by shizhediao** [comment]
Same question

**Comment by saket-maheshwary** [comment]
@shizhediao following are the instructions i used to run this module ::

1. Unzip the data files and update its path in data_process.py file
2. Run data_process.py to generate .pic file.
3. Run the file run_gan.py with any of the arguments like (best_cnn_expansion or best_cnn_li ... etc)
