### ISSUE TITLE
Pre-process procedure for PDTB-Ji dataset

### ISSUE THREAD

**Issue by hitercs** [qkaren/Adversarial-Network-for-Implicit-Discourse-Relation-Classification-ACL-2017-#2]
Hi,

Thanks for your work. I found you only release the pre-process code for PDTB-Lin. Based on the code and the description in your paper, I pre-process PDTB-Ji dataset from tacl dataset your provided. By keeping all examples in 21-22.json dataset with "Implicit" type, I got 1046 instances.
But in your paper, you say PDTB-Ji contains 1039 examples. Is there any missing conditions? 
Could you please clarify this?

Thanks!

**Comment by qkaren** [comment]
Hi Shuang,

I remember there are some instances should be filtered. The number in my
paper is consistent with previous related works. Can you check a bit about
the reason to filter? I am not able to recall exactly what is that but I am
sure you can find in somewhere.  Sorry, I am stuck with some stuff
recently, but feel free to let me know if you have any questions.

Thanks,
Lianhui

**Comment by hitercs** [comment]
Hi Lianhui,

Thanks for your reply! I will figure it out.
I have another question. I found in the data you provided, for one example, there may multiple senses and multiple connectives. But sometimes, the number of senses and connectives are not equal. I found in your code, you only extract the first connective as for all senses. It sometimes may bring some noise. 
Is this one simplified assumption? or Do you know what's the correct correspondence between connectives and senses in one example.

Best,
Shuang

**Comment by qkaren** [comment]
Hi Shuang,

Sorry for the late reply. I'm sorry that I really didn't remember the
details. My suggestion is that you can just follow the settings of previous
works as you are comparing with them. If I remember correctly there is no
standard processing. I also followed others when I was working on this
task. Good luck with your research. :)

Thanks,
Lianhui

**Comment by hitercs** [comment]
Thank you very much!
